// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * Settings is the user-facing configuration surface exposed by the
 * SettingsService. The JSON tags are preserved verbatim from the v2
 * binding so existing config.yaml files round-trip unchanged.
 */
export class Settings {
    "magickBinary": string;
    "ffmpegBinary": string;
    "maxSize": number;
    "maxImageSize": number;
    "autoLivePhoto": boolean;
    "copyOnlyExtensions": string[];
    "hardwareAccelerator": string;
    "ffmpegCustomArgs": string;
    "defaultDestDir": string;
    "excludePatterns": string[];
    "videoQuality": string;
    "maxFfmpegWorkers": number;
    "maxMagickWorkers": number;
    "collisionOption": string;
    "logLevel": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("magickBinary" in $$source)) {
            this["magickBinary"] = "";
        }
        if (!("ffmpegBinary" in $$source)) {
            this["ffmpegBinary"] = "";
        }
        if (!("maxSize" in $$source)) {
            this["maxSize"] = 0;
        }
        if (!("maxImageSize" in $$source)) {
            this["maxImageSize"] = 0;
        }
        if (!("autoLivePhoto" in $$source)) {
            this["autoLivePhoto"] = false;
        }
        if (!("copyOnlyExtensions" in $$source)) {
            this["copyOnlyExtensions"] = [];
        }
        if (!("hardwareAccelerator" in $$source)) {
            this["hardwareAccelerator"] = "";
        }
        if (!("ffmpegCustomArgs" in $$source)) {
            this["ffmpegCustomArgs"] = "";
        }
        if (!("defaultDestDir" in $$source)) {
            this["defaultDestDir"] = "";
        }
        if (!("excludePatterns" in $$source)) {
            this["excludePatterns"] = [];
        }
        if (!("videoQuality" in $$source)) {
            this["videoQuality"] = "";
        }
        if (!("maxFfmpegWorkers" in $$source)) {
            this["maxFfmpegWorkers"] = 0;
        }
        if (!("maxMagickWorkers" in $$source)) {
            this["maxMagickWorkers"] = 0;
        }
        if (!("collisionOption" in $$source)) {
            this["collisionOption"] = "";
        }
        if (!("logLevel" in $$source)) {
            this["logLevel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField5_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("copyOnlyExtensions" in $$parsedSource) {
            $$parsedSource["copyOnlyExtensions"] = $$createField5_0($$parsedSource["copyOnlyExtensions"]);
        }
        if ("excludePatterns" in $$parsedSource) {
            $$parsedSource["excludePatterns"] = $$createField9_0($$parsedSource["excludePatterns"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
