version: '3'

vars:
  VERSION:
    sh: powershell -NoProfile -Command "[Console]::Write((Get-Content wails.json | ConvertFrom-Json).info.productVersion)"

tasks:
  build:
    desc: "Build the application for production"
    cmds:
      - wails build -ldflags="-s -w"
  dev:
    desc: "Run the application in development mode"
    cmds:
      - wails dev
  release:
    desc: "Create a release zip file"
    deps: [build]
    cmds:
      - powershell -NoProfile -Command "Compress-Archive -Path build/bin/convert4share.exe -DestinationPath build/bin/convert4share-v{{.VERSION}}-windows-amd64.zip -Force"
