// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles(arg1:string[]):Promise<void>;

export function ConvertFiles(arg1:string[]):Promise<void>;

export function CopyFileToClipboard(arg1:string):Promise<void>;

export function GetContextMenuStatus():Promise<boolean>;

export function GetSettings():Promise<main.Settings>;

export function InstallContextMenu():Promise<void>;

export function OnSecondInstanceLaunch(arg1:any):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function UninstallContextMenu():Promise<void>;

export function SelectBinaryDialog():Promise<string>;

export function DetectBinaries():Promise<{[key: string]: string}>;

export function GetThumbnail(arg1:string):Promise<string>;

export function CancelJob(arg1:string):Promise<void>;

export function PauseQueue():Promise<void>;

export function ResumeQueue():Promise<void>;
