// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function ConvertFiles(arg1) {
  return window['go']['main']['App']['ConvertFiles'](arg1);
}

export function GetContextMenuStatus() {
  return window['go']['main']['App']['GetContextMenuStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InstallContextMenu() {
  return window['go']['main']['App']['InstallContextMenu']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UninstallContextMenu() {
  return window['go']['main']['App']['UninstallContextMenu']();
}

export function SelectBinaryDialog() {
  return window['go']['main']['App']['SelectBinaryDialog']();
}

export function DetectBinaries() {
  return window['go']['main']['App']['DetectBinaries']();
}
