// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function ConvertFiles(arg1) {
  return window['go']['main']['App']['ConvertFiles'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
