// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the v3 service binding for tool helpers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

/**
 * CopyFileToClipboard places the given file on the system clipboard as
 * a CF_HDROP-style file drop list (PowerShell on Windows; no-op on
 * other platforms).
 */
export function CopyFileToClipboard(path: string): $CancellablePromise<void> {
    return $Call.ByID(3175661114, path);
}

/**
 * DetectBinaries searches PATH plus standard WinGet install locations
 * for ffmpeg.exe / magick.exe and returns a map keyed by tool name.
 */
export function DetectBinaries(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2600931500).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetThumbnail generates a 200px-wide JPEG preview for the given file
 * and returns it as a `data:image/jpeg;base64,...` URL. Concurrent
 * invocations are serialised via thumbSem (capacity 1) to keep
 * ffmpeg/magick spawn pressure low.
 */
export function GetThumbnail(path: string): $CancellablePromise<string> {
    return $Call.ByID(2361688082, path);
}

/**
 * InstallTool installs the requested tool via winget (ffmpeg ->
 * Gyan.FFmpeg, magick -> ImageMagick.ImageMagick) and, if successful,
 * persists the freshly detected binary path back into viper.
 */
export function InstallTool(toolName: string): $CancellablePromise<void> {
    return $Call.ByID(1623613639, toolName);
}

/**
 * SelectBinaryDialog opens a single-select file dialog filtered to
 * executable extensions. Returns an empty string (not an error) if the
 * user cancels.
 */
export function SelectBinaryDialog(): $CancellablePromise<string> {
    return $Call.ByID(2071041579);
}

/**
 * SelectFiles opens a multi-select file dialog filtered to the media
 * formats Convert4Share understands. An empty slice (not an error) is
 * returned if the user cancels.
 */
export function SelectFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(341952521).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
