// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the v3 service binding for application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../config/models.js";

/**
 * GetSettings returns the current Settings view from viper.
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(3793606357).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings persists the given Settings to viper + the config file,
 * then notifies the rest of the app. The log-level adjustment is done
 * synchronously here so frontend feedback is immediate.
 */
export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(425062532, settings);
}

// Private type creation functions
const $$createType0 = config$0.Settings.createFrom;
