// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service owns the conversion queue plus its concurrency primitives.
 * All exported methods are bound by Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AddFiles is the v3 equivalent of the v2 App.AddFiles: validates each
 * path and emits a `file-added` event per accepted file.
 */
export function AddFiles(files: string[]): $CancellablePromise<void> {
    return $Call.ByID(2210596277, files);
}

/**
 * CancelJob cancels the in-flight conversion for the given job id (the
 * absolute source path). If the queue is paused, the pause cond is
 * broadcast so the cancelled goroutine can observe the cancellation.
 */
export function CancelJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(2770216920, id);
}

/**
 * ConvertFiles is the main entry point invoked by the frontend. It
 * runs entirely in a background goroutine so the IPC call returns
 * immediately; per-file progress is reported via `conversion-progress`
 * events and the batch terminates with `all-jobs-done`.
 */
export function ConvertFiles(files: string[]): $CancellablePromise<void> {
    return $Call.ByID(1097601557, files);
}

/**
 * EmitFilesReceived fans out a `files-received` event with the given
 * validated paths. Exposed for the main package to use when forwarding
 * files from CLI args or second-instance launches; the legacy v2
 * processPendingFiles path is gone.
 */
export function EmitFilesReceived(files: string[]): $CancellablePromise<void> {
    return $Call.ByID(3768543116, files);
}

/**
 * PauseQueue prevents any further jobs from leaving the pause loop
 * until ResumeQueue is called. Already-running ffmpeg/magick processes
 * continue to completion.
 */
export function PauseQueue(): $CancellablePromise<void> {
    return $Call.ByID(3272998542);
}

/**
 * ResumeQueue clears the pause flag and broadcasts so all blocked
 * workers re-check their state.
 */
export function ResumeQueue(): $CancellablePromise<void> {
    return $Call.ByID(388281027);
}
